sudo: false

language: ruby
rvm:
  - ruby-head
  - 2.2.5

matrix:
  allow_failures:
    - rvm: ruby-head
fast_finish: true

branches:
  only:
    - master
    - devel_branch

before_install: 'gem install bundler -v 1.13.0'

script: 'bundle exec rake acceptance'
